// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FeaturesInitParameters struct {

	// Channel Logout to be notified in your application about terminated user sessions.
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `json:"enableBackChannelLogout,omitempty" tf:"enable_back_channel_logout,omitempty"`

	// (Set of String) Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// +listType=set
	ImprovedPerformance []*string `json:"improvedPerformance,omitempty" tf:"improved_performance,omitempty"`

	// (Boolean) The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `json:"loginDefaultOrg,omitempty" tf:"login_default_org,omitempty"`

	// (Block List, Max: 1) Specify the login UI for all users and applications regardless of their preference. (see below for nested schema)
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 []LoginV2InitParameters `json:"loginV2,omitempty" tf:"login_v2,omitempty"`

	// (Boolean) If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a sid claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a `sid` claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `json:"oidcSingleV1SessionTermination,omitempty" tf:"oidc_single_v1_session_termination,omitempty"`

	// type:token-exchange grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `json:"oidcTokenExchange,omitempty" tf:"oidc_token_exchange,omitempty"`

	// (Boolean) Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `json:"permissionCheckV2,omitempty" tf:"permission_check_v2,omitempty"`

	// (Boolean) User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `json:"userSchema,omitempty" tf:"user_schema,omitempty"`
}

type FeaturesObservation struct {

	// Channel Logout to be notified in your application about terminated user sessions.
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `json:"enableBackChannelLogout,omitempty" tf:"enable_back_channel_logout,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// +listType=set
	ImprovedPerformance []*string `json:"improvedPerformance,omitempty" tf:"improved_performance,omitempty"`

	// (Boolean) The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `json:"loginDefaultOrg,omitempty" tf:"login_default_org,omitempty"`

	// (Block List, Max: 1) Specify the login UI for all users and applications regardless of their preference. (see below for nested schema)
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 []LoginV2Observation `json:"loginV2,omitempty" tf:"login_v2,omitempty"`

	// (Boolean) If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a sid claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a `sid` claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `json:"oidcSingleV1SessionTermination,omitempty" tf:"oidc_single_v1_session_termination,omitempty"`

	// type:token-exchange grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `json:"oidcTokenExchange,omitempty" tf:"oidc_token_exchange,omitempty"`

	// (Boolean) Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `json:"permissionCheckV2,omitempty" tf:"permission_check_v2,omitempty"`

	// (Boolean) User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `json:"userSchema,omitempty" tf:"user_schema,omitempty"`
}

type FeaturesParameters struct {

	// Channel Logout to be notified in your application about terminated user sessions.
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	// +kubebuilder:validation:Optional
	EnableBackChannelLogout *bool `json:"enableBackChannelLogout,omitempty" tf:"enable_back_channel_logout,omitempty"`

	// (Set of String) Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// Improves performance of specified execution paths. Possible values: IMPROVED_PERFORMANCE_PROJECT_GRANT, IMPROVED_PERFORMANCE_PROJECT, IMPROVED_PERFORMANCE_USER_GRANT, IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED
	// +kubebuilder:validation:Optional
	// +listType=set
	ImprovedPerformance []*string `json:"improvedPerformance,omitempty" tf:"improved_performance,omitempty"`

	// (Boolean) The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	// +kubebuilder:validation:Optional
	LoginDefaultOrg *bool `json:"loginDefaultOrg,omitempty" tf:"login_default_org,omitempty"`

	// (Block List, Max: 1) Specify the login UI for all users and applications regardless of their preference. (see below for nested schema)
	// Specify the login UI for all users and applications regardless of their preference.
	// +kubebuilder:validation:Optional
	LoginV2 []LoginV2Parameters `json:"loginV2,omitempty" tf:"login_v2,omitempty"`

	// (Boolean) If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a sid claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id_token with a `sid` claim as id_token_hint on the end_session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	// +kubebuilder:validation:Optional
	OidcSingleV1SessionTermination *bool `json:"oidcSingleV1SessionTermination,omitempty" tf:"oidc_single_v1_session_termination,omitempty"`

	// type:token-exchange grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	// +kubebuilder:validation:Optional
	OidcTokenExchange *bool `json:"oidcTokenExchange,omitempty" tf:"oidc_token_exchange,omitempty"`

	// (Boolean) Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	// +kubebuilder:validation:Optional
	PermissionCheckV2 *bool `json:"permissionCheckV2,omitempty" tf:"permission_check_v2,omitempty"`

	// (Boolean) User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	// +kubebuilder:validation:Optional
	UserSchema *bool `json:"userSchema,omitempty" tf:"user_schema,omitempty"`
}

type LoginV2InitParameters struct {

	// (String) Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	// Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	BaseURI *string `json:"baseUri,omitempty" tf:"base_uri,omitempty"`

	// (Boolean) Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	// Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`
}

type LoginV2Observation struct {

	// (String) Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	// Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	BaseURI *string `json:"baseUri,omitempty" tf:"base_uri,omitempty"`

	// (Boolean) Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	// Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`
}

type LoginV2Parameters struct {

	// (String) Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	// Optionally specify a base uri of the login UI. If unspecified the default URI will be used.
	// +kubebuilder:validation:Optional
	BaseURI *string `json:"baseUri,omitempty" tf:"base_uri,omitempty"`

	// (Boolean) Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	// Require that all users must use the new login UI. If enabled, all users will be redirected to the login V2 regardless of the application's preference.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`
}

// FeaturesSpec defines the desired state of Features
type FeaturesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeaturesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeaturesInitParameters `json:"initProvider,omitempty"`
}

// FeaturesStatus defines the observed state of Features.
type FeaturesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeaturesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Features is the Schema for the Featuress API. Resource representing the feature flags configuration for the system.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type Features struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeaturesSpec   `json:"spec"`
	Status            FeaturesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeaturesList contains a list of Featuress
type FeaturesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Features `json:"items"`
}

// Repository type metadata.
var (
	Features_Kind             = "Features"
	Features_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Features_Kind}.String()
	Features_KindAPIVersion   = Features_Kind + "." + CRDGroupVersion.String()
	Features_GroupVersionKind = CRDGroupVersion.WithKind(Features_Kind)
)

func init() {
	SchemeBuilder.Register(&Features{}, &FeaturesList{})
}
