apiVersion: org.zitadel.crossplane.io/v1alpha1
kind: IdpApple
metadata:
  annotations:
    meta.upbound.io/example-id: org/v1alpha1/idpapple
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: com.example.app
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    keyId: FGHIJ67890
    name: Apple
    orgId: ${data.zitadel_org.default.id}
    privateKeySecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
    scopes:
    - name
    - email
    teamId: ABCDE12345
