apiVersion: smtp.zitadel.m.crossplane.io/v1alpha1
kind: Config
metadata:
  annotations:
    meta.upbound.io/example-id: smtp/v1alpha1/config
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    host: localhost:25
    passwordSecretRef:
      key: example-key
      name: example-secret
    replyToAddress: replyto@example.com
    senderAddress: sender@example.com
    senderName: no-reply
    tls: true
    user: user
