apiVersion: default.zitadel.crossplane.io/v1alpha1
kind: NotificationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/notificationpolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    passwordChange: false
