apiVersion: default.zitadel.crossplane.io/v1alpha1
kind: PasswordAgePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/passwordagepolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    expireWarnDays: 5
    maxAgeDays: 30
