apiVersion: default.zitadel.crossplane.io/v1alpha1
kind: SecuritySettings
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/securitysettings
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    enableImpersonation: true
