//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInitParameters) DeepCopyInto(out *PolicyInitParameters) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInitParameters.
func (in *PolicyInitParameters) DeepCopy() *PolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObservation) DeepCopyInto(out *PolicyObservation) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.FontURL != nil {
		in, out := &in.FontURL, &out.FontURL
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.IconURL != nil {
		in, out := &in.IconURL, &out.IconURL
		*out = new(string)
		**out = **in
	}
	if in.IconURLDark != nil {
		in, out := &in.IconURLDark, &out.IconURLDark
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.LogoURLDark != nil {
		in, out := &in.LogoURLDark, &out.LogoURLDark
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObservation.
func (in *PolicyObservation) DeepCopy() *PolicyObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyParameters) DeepCopyInto(out *PolicyParameters) {
	*out = *in
	if in.BackgroundColor != nil {
		in, out := &in.BackgroundColor, &out.BackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.BackgroundColorDark != nil {
		in, out := &in.BackgroundColorDark, &out.BackgroundColorDark
		*out = new(string)
		**out = **in
	}
	if in.DisableWatermark != nil {
		in, out := &in.DisableWatermark, &out.DisableWatermark
		*out = new(bool)
		**out = **in
	}
	if in.FontColor != nil {
		in, out := &in.FontColor, &out.FontColor
		*out = new(string)
		**out = **in
	}
	if in.FontColorDark != nil {
		in, out := &in.FontColorDark, &out.FontColorDark
		*out = new(string)
		**out = **in
	}
	if in.FontHash != nil {
		in, out := &in.FontHash, &out.FontHash
		*out = new(string)
		**out = **in
	}
	if in.FontPath != nil {
		in, out := &in.FontPath, &out.FontPath
		*out = new(string)
		**out = **in
	}
	if in.HideLoginNameSuffix != nil {
		in, out := &in.HideLoginNameSuffix, &out.HideLoginNameSuffix
		*out = new(bool)
		**out = **in
	}
	if in.IconDarkHash != nil {
		in, out := &in.IconDarkHash, &out.IconDarkHash
		*out = new(string)
		**out = **in
	}
	if in.IconDarkPath != nil {
		in, out := &in.IconDarkPath, &out.IconDarkPath
		*out = new(string)
		**out = **in
	}
	if in.IconHash != nil {
		in, out := &in.IconHash, &out.IconHash
		*out = new(string)
		**out = **in
	}
	if in.IconPath != nil {
		in, out := &in.IconPath, &out.IconPath
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkHash != nil {
		in, out := &in.LogoDarkHash, &out.LogoDarkHash
		*out = new(string)
		**out = **in
	}
	if in.LogoDarkPath != nil {
		in, out := &in.LogoDarkPath, &out.LogoDarkPath
		*out = new(string)
		**out = **in
	}
	if in.LogoHash != nil {
		in, out := &in.LogoHash, &out.LogoHash
		*out = new(string)
		**out = **in
	}
	if in.LogoPath != nil {
		in, out := &in.LogoPath, &out.LogoPath
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColor != nil {
		in, out := &in.PrimaryColor, &out.PrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PrimaryColorDark != nil {
		in, out := &in.PrimaryColorDark, &out.PrimaryColorDark
		*out = new(string)
		**out = **in
	}
	if in.SetActive != nil {
		in, out := &in.SetActive, &out.SetActive
		*out = new(bool)
		**out = **in
	}
	if in.ThemeMode != nil {
		in, out := &in.ThemeMode, &out.ThemeMode
		*out = new(string)
		**out = **in
	}
	if in.WarnColor != nil {
		in, out := &in.WarnColor, &out.WarnColor
		*out = new(string)
		**out = **in
	}
	if in.WarnColorDark != nil {
		in, out := &in.WarnColorDark, &out.WarnColorDark
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyParameters.
func (in *PolicyParameters) DeepCopy() *PolicyParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}
