apiVersion: instance.zitadel.crossplane.io/v1alpha1
kind: Restrictions
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/restrictions
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allowedLanguages:
    - en
    - de
    disallowPublicOrgRegistration: true
