apiVersion: instance.zitadel.crossplane.io/v1alpha1
kind: SecretGenerator
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/secretgenerator
  labels:
    testing.upbound.io/example-name: password_reset
  name: password-reset
spec:
  forProvider:
    expiry: 15m
    generatorType: password_reset_code
    includeDigits: true
    includeLowerLetters: true
    includeSymbols: false
    includeUpperLetters: true
    length: 8
