// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/zitadel/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Actions.
func (mg *Actions) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ActionIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ActionIdsRefs,
		Selector:      mg.Spec.ForProvider.ActionIdsSelector,
		To: reference.To{
			List:    &v1alpha1.ActionList{},
			Managed: &v1alpha1.Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ActionIds")
	}
	mg.Spec.ForProvider.ActionIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ActionIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ActionIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ActionIdsRefs,
		Selector:      mg.Spec.InitProvider.ActionIdsSelector,
		To: reference.To{
			List:    &v1alpha1.ActionList{},
			Managed: &v1alpha1.Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ActionIds")
	}
	mg.Spec.InitProvider.ActionIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ActionIdsRefs = mrsp.ResolvedReferences

	return nil
}
