apiVersion: action.zitadel.crossplane.io/v1alpha1
kind: ExecutionEvent
metadata:
  annotations:
    meta.upbound.io/example-id: action/v1alpha1/executionevent
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    event: user.human.added
    targetIds:
    - ${zitadel_action_target.default.id}

---

apiVersion: action.zitadel.crossplane.io/v1alpha1
kind: Target
metadata:
  annotations:
    meta.upbound.io/example-id: action/v1alpha1/executionevent
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    endpoint: https://example.com/webhooks/events
    interruptOnError: false
    name: event-webhook
    targetType: REST_ASYNC
    timeout: 10s
