apiVersion: password.zitadel.crossplane.io/v1alpha1
kind: AgePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: password/v1alpha1/agepolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    expireWarnDays: 5
    maxAgeDays: 30
    orgId: ${data.zitadel_org.default.id}
