// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ResetMessageTextInitParameters struct {

	// (String)
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String)
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// (String)
	Greeting *string `json:"greeting,omitempty" tf:"greeting,omitempty"`

	// (String)
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// (String)
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String)
	PreHeader *string `json:"preHeader,omitempty" tf:"pre_header,omitempty"`

	// (String)
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String)
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ResetMessageTextObservation struct {

	// (String)
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String)
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// (String)
	Greeting *string `json:"greeting,omitempty" tf:"greeting,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// (String)
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String)
	PreHeader *string `json:"preHeader,omitempty" tf:"pre_header,omitempty"`

	// (String)
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String)
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ResetMessageTextParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	ButtonText *string `json:"buttonText,omitempty" tf:"button_text,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FooterText *string `json:"footerText,omitempty" tf:"footer_text,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Greeting *string `json:"greeting,omitempty" tf:"greeting,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PreHeader *string `json:"preHeader,omitempty" tf:"pre_header,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// ResetMessageTextSpec defines the desired state of ResetMessageText
type ResetMessageTextSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ResetMessageTextParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ResetMessageTextInitParameters `json:"initProvider,omitempty"`
}

// ResetMessageTextStatus defines the observed state of ResetMessageText.
type ResetMessageTextStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ResetMessageTextObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ResetMessageText is the Schema for the ResetMessageTexts API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type ResetMessageText struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.language) || (has(self.initProvider) && has(self.initProvider.language))",message="spec.forProvider.language is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.orgId) || (has(self.initProvider) && has(self.initProvider.orgId))",message="spec.forProvider.orgId is a required parameter"
	Spec   ResetMessageTextSpec   `json:"spec"`
	Status ResetMessageTextStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ResetMessageTextList contains a list of ResetMessageTexts
type ResetMessageTextList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResetMessageText `json:"items"`
}

// Repository type metadata.
var (
	ResetMessageText_Kind             = "ResetMessageText"
	ResetMessageText_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ResetMessageText_Kind}.String()
	ResetMessageText_KindAPIVersion   = ResetMessageText_Kind + "." + CRDGroupVersion.String()
	ResetMessageText_GroupVersionKind = CRDGroupVersion.WithKind(ResetMessageText_Kind)
)

func init() {
	SchemeBuilder.Register(&ResetMessageText{}, &ResetMessageTextList{})
}
