// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MetadataInitParameters struct {

	// (String) Key of the metadata entry
	// Key of the metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) Value of the metadata entry. For binary data, use base64encode function.
	// Value of the metadata entry. For binary data, use base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MetadataObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Key of the metadata entry
	// Key of the metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) Value of the metadata entry. For binary data, use base64encode function.
	// Value of the metadata entry. For binary data, use base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MetadataParameters struct {

	// (String) Key of the metadata entry
	// Key of the metadata entry
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) Value of the metadata entry. For binary data, use base64encode function.
	// Value of the metadata entry. For binary data, use base64encode function.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// MetadataSpec defines the desired state of Metadata
type MetadataSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MetadataParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MetadataInitParameters `json:"initProvider,omitempty"`
}

// MetadataStatus defines the observed state of Metadata.
type MetadataStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MetadataObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Metadata is the Schema for the Metadatas API. Resource representing metadata of an organization in ZITADEL. This resource manages a single key-value pair.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type Metadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organizationId) || (has(self.initProvider) && has(self.initProvider.organizationId))",message="spec.forProvider.organizationId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   MetadataSpec   `json:"spec"`
	Status MetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MetadataList contains a list of Metadatas
type MetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Metadata `json:"items"`
}

// Repository type metadata.
var (
	Metadata_Kind             = "Metadata"
	Metadata_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Metadata_Kind}.String()
	Metadata_KindAPIVersion   = Metadata_Kind + "." + CRDGroupVersion.String()
	Metadata_GroupVersionKind = CRDGroupVersion.WithKind(Metadata_Kind)
)

func init() {
	SchemeBuilder.Register(&Metadata{}, &MetadataList{})
}
