// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OrganizationAdminsInitParameters struct {

	// (List of String)
	Roles []*string `json:"roles,omitempty" tf:"roles"`

	// (String)
	UserID *string `json:"userId,omitempty" tf:"user_id"`
}

type OrganizationAdminsObservation struct {

	// (List of String)
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type OrganizationAdminsParameters struct {

	// (List of String)
	// +kubebuilder:validation:Optional
	Roles []*string `json:"roles,omitempty" tf:"roles"`

	// (String)
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id"`
}

type OrganizationInitParameters struct {

	// (List of Object) List of users to be granted organization admin roles (see below for nested schema)
	// List of users to be granted organization admin roles
	Admins []OrganizationAdminsInitParameters `json:"admins,omitempty" tf:"admins,omitempty"`

	// (String) Name of the org
	// Name of the org
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Custom unique identifier for the organization
	// Custom unique identifier for the organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`
}

type OrganizationObservation struct {

	// (List of Object) List of users to be granted organization admin roles (see below for nested schema)
	// List of users to be granted organization admin roles
	Admins []OrganizationAdminsObservation `json:"admins,omitempty" tf:"admins,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the org
	// Name of the org
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Custom unique identifier for the organization
	// Custom unique identifier for the organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) Primary domain of the org
	// Primary domain of the org
	PrimaryDomain *string `json:"primaryDomain,omitempty" tf:"primary_domain,omitempty"`

	// (String) State of the org
	// State of the org
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type OrganizationParameters struct {

	// (List of Object) List of users to be granted organization admin roles (see below for nested schema)
	// List of users to be granted organization admin roles
	// +kubebuilder:validation:Optional
	Admins []OrganizationAdminsParameters `json:"admins,omitempty" tf:"admins,omitempty"`

	// (String) Name of the org
	// Name of the org
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Custom unique identifier for the organization
	// Custom unique identifier for the organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`
}

// OrganizationSpec defines the desired state of Organization
type OrganizationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationInitParameters `json:"initProvider,omitempty"`
}

// OrganizationStatus defines the observed state of Organization.
type OrganizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Organization is the Schema for the Organizations API. Resource representing an organization in ZITADEL, which is the highest level after the instance and contains several other resource including policies if the configuration differs to the default policies on the instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organizations
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

// Repository type metadata.
var (
	Organization_Kind             = "Organization"
	Organization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Organization_Kind}.String()
	Organization_KindAPIVersion   = Organization_Kind + "." + CRDGroupVersion.String()
	Organization_GroupVersionKind = CRDGroupVersion.WithKind(Organization_Kind)
)

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
