apiVersion: lockout.zitadel.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: lockout/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    maxPasswordAttempts: "5"
    orgId: ${data.zitadel_org.default.id}
