// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProviderHTTPInitParameters struct {

	// (String) Description of the SMS provider.
	// Description of the SMS provider.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Http endpoint which is used to send the SMS.
	// Http endpoint which is used to send the SMS.
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (String) Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey *string `json:"expirationSigningKey,omitempty" tf:"expiration_signing_key,omitempty"`

	// (Boolean) Set the SMS provider as active after creating/updating.
	// Set the SMS provider as active after creating/updating.
	SetActive *bool `json:"setActive,omitempty" tf:"set_active,omitempty"`
}

type ProviderHTTPObservation struct {

	// (String) Description of the SMS provider.
	// Description of the SMS provider.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Http endpoint which is used to send the SMS.
	// Http endpoint which is used to send the SMS.
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (String) Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	ExpirationSigningKey *string `json:"expirationSigningKey,omitempty" tf:"expiration_signing_key,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Set the SMS provider as active after creating/updating.
	// Set the SMS provider as active after creating/updating.
	SetActive *bool `json:"setActive,omitempty" tf:"set_active,omitempty"`
}

type ProviderHTTPParameters struct {

	// (String) Description of the SMS provider.
	// Description of the SMS provider.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Http endpoint which is used to send the SMS.
	// Http endpoint which is used to send the SMS.
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (String) Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	// Expiration duration for the signing key. When set during update, the old signing key will remain valid for the specified duration to allow for a graceful key rotation.
	// +kubebuilder:validation:Optional
	ExpirationSigningKey *string `json:"expirationSigningKey,omitempty" tf:"expiration_signing_key,omitempty"`

	// (Boolean) Set the SMS provider as active after creating/updating.
	// Set the SMS provider as active after creating/updating.
	// +kubebuilder:validation:Optional
	SetActive *bool `json:"setActive,omitempty" tf:"set_active,omitempty"`
}

// ProviderHTTPSpec defines the desired state of ProviderHTTP
type ProviderHTTPSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProviderHTTPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderHTTPInitParameters `json:"initProvider,omitempty"`
}

// ProviderHTTPStatus defines the observed state of ProviderHTTP.
type ProviderHTTPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderHTTPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProviderHTTP is the Schema for the ProviderHTTPs API. Resource representing the HTTP SMS provider configuration of an instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type ProviderHTTP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endpoint) || (has(self.initProvider) && has(self.initProvider.endpoint))",message="spec.forProvider.endpoint is a required parameter"
	Spec   ProviderHTTPSpec   `json:"spec"`
	Status ProviderHTTPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderHTTPList contains a list of ProviderHTTPs
type ProviderHTTPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProviderHTTP `json:"items"`
}

// Repository type metadata.
var (
	ProviderHTTP_Kind             = "ProviderHTTP"
	ProviderHTTP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProviderHTTP_Kind}.String()
	ProviderHTTP_KindAPIVersion   = ProviderHTTP_Kind + "." + CRDGroupVersion.String()
	ProviderHTTP_GroupVersionKind = CRDGroupVersion.WithKind(ProviderHTTP_Kind)
)

func init() {
	SchemeBuilder.Register(&ProviderHTTP{}, &ProviderHTTPList{})
}
