//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageText) DeepCopyInto(out *ClaimedMessageText) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageText.
func (in *ClaimedMessageText) DeepCopy() *ClaimedMessageText {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageText)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClaimedMessageText) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextInitParameters) DeepCopyInto(out *ClaimedMessageTextInitParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextInitParameters.
func (in *ClaimedMessageTextInitParameters) DeepCopy() *ClaimedMessageTextInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextList) DeepCopyInto(out *ClaimedMessageTextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClaimedMessageText, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextList.
func (in *ClaimedMessageTextList) DeepCopy() *ClaimedMessageTextList {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClaimedMessageTextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextObservation) DeepCopyInto(out *ClaimedMessageTextObservation) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextObservation.
func (in *ClaimedMessageTextObservation) DeepCopy() *ClaimedMessageTextObservation {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextParameters) DeepCopyInto(out *ClaimedMessageTextParameters) {
	*out = *in
	if in.ButtonText != nil {
		in, out := &in.ButtonText, &out.ButtonText
		*out = new(string)
		**out = **in
	}
	if in.FooterText != nil {
		in, out := &in.FooterText, &out.FooterText
		*out = new(string)
		**out = **in
	}
	if in.Greeting != nil {
		in, out := &in.Greeting, &out.Greeting
		*out = new(string)
		**out = **in
	}
	if in.Language != nil {
		in, out := &in.Language, &out.Language
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.PreHeader != nil {
		in, out := &in.PreHeader, &out.PreHeader
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextParameters.
func (in *ClaimedMessageTextParameters) DeepCopy() *ClaimedMessageTextParameters {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextSpec) DeepCopyInto(out *ClaimedMessageTextSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextSpec.
func (in *ClaimedMessageTextSpec) DeepCopy() *ClaimedMessageTextSpec {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimedMessageTextStatus) DeepCopyInto(out *ClaimedMessageTextStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimedMessageTextStatus.
func (in *ClaimedMessageTextStatus) DeepCopy() *ClaimedMessageTextStatus {
	if in == nil {
		return nil
	}
	out := new(ClaimedMessageTextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policy) DeepCopyInto(out *Policy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policy.
func (in *Policy) DeepCopy() *Policy {
	if in == nil {
		return nil
	}
	out := new(Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Policy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInitParameters) DeepCopyInto(out *PolicyInitParameters) {
	*out = *in
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInitParameters.
func (in *PolicyInitParameters) DeepCopy() *PolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyList) DeepCopyInto(out *PolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Policy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyList.
func (in *PolicyList) DeepCopy() *PolicyList {
	if in == nil {
		return nil
	}
	out := new(PolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyObservation) DeepCopyInto(out *PolicyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyObservation.
func (in *PolicyObservation) DeepCopy() *PolicyObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyParameters) DeepCopyInto(out *PolicyParameters) {
	*out = *in
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.SMTPSenderAddressMatchesInstanceDomain != nil {
		in, out := &in.SMTPSenderAddressMatchesInstanceDomain, &out.SMTPSenderAddressMatchesInstanceDomain
		*out = new(bool)
		**out = **in
	}
	if in.UserLoginMustBeDomain != nil {
		in, out := &in.UserLoginMustBeDomain, &out.UserLoginMustBeDomain
		*out = new(bool)
		**out = **in
	}
	if in.ValidateOrgDomains != nil {
		in, out := &in.ValidateOrgDomains, &out.ValidateOrgDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyParameters.
func (in *PolicyParameters) DeepCopy() *PolicyParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStatus) DeepCopyInto(out *PolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStatus.
func (in *PolicyStatus) DeepCopy() *PolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyStatus)
	in.DeepCopyInto(out)
	return out
}
