apiVersion: sms.zitadel.crossplane.io/v1alpha1
kind: ProviderHTTP
metadata:
  annotations:
    meta.upbound.io/example-id: sms/v1alpha1/providerhttp
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: provider description
    endpoint: https://relay.example.com/provider
    setActive: false
