apiVersion: application.zitadel.crossplane.io/v1alpha1
kind: SAML
metadata:
  annotations:
    meta.upbound.io/example-id: application/v1alpha1/saml
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    metadataXmlSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
    name: applicationapi
    orgId: ${data.zitadel_org.default.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
