apiVersion: action.zitadel.m.crossplane.io/v1alpha1
kind: TargetPublicKey
metadata:
  annotations:
    meta.upbound.io/example-id: action/v1alpha1/targetpublickey
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    publicKey: ${file("path/to/public_key.pem")}
    targetId: ${zitadel_action_target.default.id}
