// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/action/v1alpha1"
	v1alpha1active "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/active/v1alpha1"
	v1alpha1application "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/application/v1alpha1"
	v1alpha1default "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/default/v1alpha1"
	v1alpha1domain "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/domain/v1alpha1"
	v1alpha1email "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/email/v1alpha1"
	v1alpha1idp "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/idp/v1alpha1"
	v1alpha1init "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/init/v1alpha1"
	v1alpha1instance "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/instance/v1alpha1"
	v1alpha1label "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/label/v1alpha1"
	v1alpha1lockout "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/lockout/v1alpha1"
	v1alpha1login "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/login/v1alpha1"
	v1alpha1notification "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/notification/v1alpha1"
	v1alpha1org "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/org/v1alpha1"
	v1alpha1organization "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/organization/v1alpha1"
	v1alpha1password "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/password/v1alpha1"
	v1alpha1passwordless "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/passwordless/v1alpha1"
	v1alpha1privacy "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/privacy/v1alpha1"
	v1alpha1project "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/project/v1alpha1"
	v1alpha1sms "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/sms/v1alpha1"
	v1alpha1smtp "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/smtp/v1alpha1"
	v1alpha1system "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/system/v1alpha1"
	v1alpha1trigger "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/trigger/v1alpha1"
	v1alpha1user "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/user/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/v1beta1"
	v1alpha1verify "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/verify/v1alpha1"
	v1alpha1zitadel "github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/zitadel/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1active.SchemeBuilder.AddToScheme,
		v1alpha1application.SchemeBuilder.AddToScheme,
		v1alpha1default.SchemeBuilder.AddToScheme,
		v1alpha1domain.SchemeBuilder.AddToScheme,
		v1alpha1email.SchemeBuilder.AddToScheme,
		v1alpha1idp.SchemeBuilder.AddToScheme,
		v1alpha1init.SchemeBuilder.AddToScheme,
		v1alpha1instance.SchemeBuilder.AddToScheme,
		v1alpha1label.SchemeBuilder.AddToScheme,
		v1alpha1lockout.SchemeBuilder.AddToScheme,
		v1alpha1login.SchemeBuilder.AddToScheme,
		v1alpha1notification.SchemeBuilder.AddToScheme,
		v1alpha1org.SchemeBuilder.AddToScheme,
		v1alpha1organization.SchemeBuilder.AddToScheme,
		v1alpha1password.SchemeBuilder.AddToScheme,
		v1alpha1passwordless.SchemeBuilder.AddToScheme,
		v1alpha1privacy.SchemeBuilder.AddToScheme,
		v1alpha1project.SchemeBuilder.AddToScheme,
		v1alpha1sms.SchemeBuilder.AddToScheme,
		v1alpha1smtp.SchemeBuilder.AddToScheme,
		v1alpha1system.SchemeBuilder.AddToScheme,
		v1alpha1trigger.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1verify.SchemeBuilder.AddToScheme,
		v1alpha1zitadel.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
