apiVersion: idp.zitadel.m.crossplane.io/v1alpha1
kind: Gitlab
metadata:
  annotations:
    meta.upbound.io/example-id: idp/v1alpha1/gitlab
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 15765e...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitLab
    scopes:
    - openid
    - profile
    - email
