// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TargetPublicKeyInitParameters struct {

	// (String) The expiration date of the public key in RFC3339 format.
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate *string `json:"expirationDate,omitempty" tf:"expiration_date,omitempty"`

	// (String) The public key in PEM format (RSA or EC).
	// The public key in PEM format (RSA or EC).
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (String) The ID of the action target to add the public key to.
	// The ID of the action target to add the public key to.
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`
}

type TargetPublicKeyObservation struct {

	// (Boolean) Whether the public key is active and used for payload encryption.
	// Whether the public key is active and used for payload encryption.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) The date the public key was added.
	// The date the public key was added.
	CreationDate *string `json:"creationDate,omitempty" tf:"creation_date,omitempty"`

	// (String) The expiration date of the public key in RFC3339 format.
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate *string `json:"expirationDate,omitempty" tf:"expiration_date,omitempty"`

	// (String) The fingerprint of the public key.
	// The fingerprint of the public key.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The ID of the public key, used as 'kid' in the JWE header.
	// The ID of the public key, used as 'kid' in the JWE header.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) The public key in PEM format (RSA or EC).
	// The public key in PEM format (RSA or EC).
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (String) The ID of the action target to add the public key to.
	// The ID of the action target to add the public key to.
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`
}

type TargetPublicKeyParameters struct {

	// (String) The expiration date of the public key in RFC3339 format.
	// The expiration date of the public key in RFC3339 format.
	// +kubebuilder:validation:Optional
	ExpirationDate *string `json:"expirationDate,omitempty" tf:"expiration_date,omitempty"`

	// (String) The public key in PEM format (RSA or EC).
	// The public key in PEM format (RSA or EC).
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (String) The ID of the action target to add the public key to.
	// The ID of the action target to add the public key to.
	// +kubebuilder:validation:Optional
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`
}

// TargetPublicKeySpec defines the desired state of TargetPublicKey
type TargetPublicKeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TargetPublicKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TargetPublicKeyInitParameters `json:"initProvider,omitempty"`
}

// TargetPublicKeyStatus defines the observed state of TargetPublicKey.
type TargetPublicKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TargetPublicKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TargetPublicKey is the Schema for the TargetPublicKeys API. Resource representing a public key for an action target, used for payload encryption.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type TargetPublicKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publicKey) || (has(self.initProvider) && has(self.initProvider.publicKey))",message="spec.forProvider.publicKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetId) || (has(self.initProvider) && has(self.initProvider.targetId))",message="spec.forProvider.targetId is a required parameter"
	Spec   TargetPublicKeySpec   `json:"spec"`
	Status TargetPublicKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TargetPublicKeyList contains a list of TargetPublicKeys
type TargetPublicKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetPublicKey `json:"items"`
}

// Repository type metadata.
var (
	TargetPublicKey_Kind             = "TargetPublicKey"
	TargetPublicKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TargetPublicKey_Kind}.String()
	TargetPublicKey_KindAPIVersion   = TargetPublicKey_Kind + "." + CRDGroupVersion.String()
	TargetPublicKey_GroupVersionKind = CRDGroupVersion.WithKind(TargetPublicKey_Kind)
)

func init() {
	SchemeBuilder.Register(&TargetPublicKey{}, &TargetPublicKeyList{})
}
