apiVersion: application.zitadel.m.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: application/v1alpha1/key
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    appId: ${data.zitadel_application_api.default.id}
    expirationDate: "2519-04-01T08:45:00Z"
    keyType: KEY_TYPE_JSON
    orgId: ${data.zitadel_org.default.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
