name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

permissions:
  contents: write

jobs:
  tag:
    uses: upbound/official-providers-ci/.github/workflows/provider-tag.yml@89655794e12209e2cd0caea68f13dc4e18e5c4a8 # main
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
